version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 5672:15672
  mail:
    container_name: ${COMPOSE_PROJECT_NAME}_mail
    domainname: local
    hostname: mail
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - VIRTUAL_HOST=mail.local
      - VIRTUAL_PORT=8025
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27018:27018
    restart: unless-stopped
  webserver:
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    build:
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
      - 8005:80
  redis:
    image: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}

  mysql:
    image: "mysql:latest"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: booking
    ports:
      - 127.0.0.1:13306:3306
    volumes:
      - /mysql/var/lib/mysql
    
volumes:
  mysql:
    name: mysql-${COMPOSE_PROJECT_NAME}